### ISSUE TITLE
Error when switch to another video

### ISSUE THREAD

**Issue by shahmirzali49** [ayahsujana/last_pod_player#1]
my code:

```
class ListeningDetailPage extends HookConsumerWidget {
  const ListeningDetailPage({required this.video, super.key});
  final VideoModel video;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final controller = useRef<PodPlayerController?>(null);
    final videos = ref.watch(videosProvider);
    final scrollController = useScrollController();

    useEffect(() {
      controller.value = PodPlayerController(
        podPlayerConfig: const PodPlayerConfig(
          autoPlay: true,          
        ),
        playVideoFrom: PlayVideoFrom.youtube(
          video.link,    
        ),
      )..initialise();
      return controller.value?.dispose;
    }, []);
    if (videos.hasError) {
      return ElephantReadidngBackgroundWidget(
        child: Material(
          color: Colors.transparent,
          child: Column(
            children: [
              Padding(
                padding: context.paddingOnly(
                  top: 16.h,
                  left: 20.w,
                  right: 30.w,
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    InkWell(
                      onTap: () {
                        Navigator.pop(context);
                      },
                      overlayColor: MaterialStateProperty.all(
                          const Color(0xff133B56).withOpacity(0.12)),
                      borderRadius: BorderRadius.circular(32.r),
                      child: Padding(
                        padding: EdgeInsets.all(10.r),
                        child: Text(
                          String.fromCharCode(
                              Icons.arrow_back_ios_new_rounded.codePoint),
                          style: TextStyle(
                            inherit: false,
                            color: const Color(0xff133B56),
                            fontSize: 26.r,
                            fontWeight: fWeightBold,
                            fontFamily:
                                Icons.arrow_back_ios_new_rounded.fontFamily,
                            package:
                                Icons.arrow_back_ios_new_rounded.fontPackage,
                          ),
                        ),
                      ),
                    ),
                    const MenuDrawerWidget(
                      currentRoute: 'ListeningDetailPage',
                    ),
                  ],
                ),
              ),
              Expanded(
                child: Padding(
                  padding: context.paddingSymmetric(0, 20.w),
                  child: ErrorInfoWidget(
                    error: videos.error!,
                  ),
                ),
              ),
            ],
          ),
        ),
      );
    }
    return ElephantReadidngBackgroundWidget(
      child: Material(
        color: Colors.transparent,
        child: Column(
          children: [
            Padding(
              padding: context.paddingOnly(
                top: 16.h,
                left: 20.w,
                right: 30.w,
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  InkWell(
                    onTap: () {
                      Navigator.pop(context);
                    },
                    overlayColor: MaterialStateProperty.all(
                        const Color(0xff133B56).withOpacity(0.12)),
                    borderRadius: BorderRadius.circular(32.r),
                    child: Padding(
                      padding: EdgeInsets.all(10.r),
                      child: Text(
                        String.fromCharCode(
                            Icons.arrow_back_ios_new_rounded.codePoint),
                        style: TextStyle(
                          inherit: false,
                          color: const Color(0xff133B56),
                          fontSize: 26.r,
                          fontWeight: fWeightBold,
                          fontFamily:
                              Icons.arrow_back_ios_new_rounded.fontFamily,
                          package: Icons.arrow_back_ios_new_rounded.fontPackage,
                        ),
                      ),
                    ),
                  ),
                  const MenuDrawerWidget(
                    currentRoute: 'ListeningDetailPage',
                  ),
                ],
              ),
            ),
            18.verticalSpace,
            Container(
              decoration: BoxDecoration(
                color: Colors.white,
                boxShadow: [
                  BoxShadow(
                    color: Colors.grey.withOpacity(0.1),
                    blurRadius: 2,
                    offset: const Offset(0, 3),
                  ),
                ],
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  PodVideoPlayer(
                    controller: controller.value!,
                    podPlayerLabels: const PodPlayerLabels(
                      loopVideo: 'Təkrarla',
                      quality: 'Keyfiyyət',
                      playbackSpeed: 'Sürət',
                    ),
                  ),
                  8.verticalSpace,
                  Padding(
                    padding: context.paddingSymmetric(14.spMin, 20.w),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          video.title,
                          style: context.textTheme.headlineSmall!.copyWith(
                            fontFamily: FontFamily.JosefinSans.value,
                            fontWeight: fWeightBold,
                            color: const Color(0xff133B56),
                          ),
                        ),
                        10.verticalSpace,
                        Text(
                          video.description,
                          style: context.textTheme.bodyLarge!.copyWith(
                            fontFamily: FontFamily.JosefinSans.value,
                            fontWeight: fWeightNormal,
                            color: const Color(0xff133B56),
                          ),
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            24.verticalSpace,
            Expanded(
              child: videos.when(
                data: (data) {
                  return NotificationListener(
                    onNotification: (ScrollNotification notification) {
                      if (notification is ScrollEndNotification &&
                          scrollController.position.extentAfter < 300 &&
                          data.apiProgressStillContinuing == false &&
                          data.hasReachedEndOfResults == false &&
                          data.nextPage != null) {
                        ref.read(videosProvider.notifier).getNextVideos(
                              page: data.nextPage!,
                            );
                      }

                      return true;
                    },
                    child: ScrollConfiguration(
                      behavior:
                          const ScrollBehavior().copyWith(overscroll: false),
                      child: ListView.separated(
                        controller: scrollController,
                        itemCount: data.hasReachedEndOfResults
                            ? data.results.length
                            : data.results.length + 1,
                        shrinkWrap: true,
                        padding: context.paddingSymmetric(10.h, 30.w),
                        separatorBuilder: (context, index) => 20.verticalSpace,
                        itemBuilder: (context, index) {
                          return index < data.results.length
                              ? InkWell(
                                  overlayColor: WidgetStateProperty.all(
                                      Colors.transparent),
                                  onTap: () {
                                    Navigator.pushReplacement(
                                      context,
                                      NoDurationRoute(
                                        builder: (context) =>
                                            ListeningDetailPage(
                                          video: data.results[index],
                                        ),
                                      ),
                                    );
                                  },
                                  child: Container(
                                    // margin: context.paddingSymmetric(16.h, 28.w),
                                    decoration: BoxDecoration(
                                      color: Colors.white,
                                      borderRadius: BorderRadius.circular(25.r),
                                      boxShadow: [
                                        BoxShadow(
                                          color: Colors.black.withOpacity(0.1),
                                          blurRadius: 6,
                                          offset: const Offset(0, 3),
                                        ),
                                      ],
                                    ),
                                    child: Row(
                                      mainAxisAlignment:
                                          MainAxisAlignment.start,
                                      children: [
                                        Container(
                                          height: 90.h,
                                          width: 120.w,
                                          decoration: BoxDecoration(
                                            borderRadius:
                                                BorderRadius.circular(20.r),
                                            image: DecorationImage(
                                              image: NetworkImage(
                                                  'https://img.youtube.com/vi/${extractYouTubeId(data.results[index].link)}/maxresdefault.jpg'),
                                              fit: BoxFit.cover,
                                            ),
                                          ),
                                          child: Center(
                                            child: Container(
                                              decoration: BoxDecoration(
                                                color: const Color(0xffFF507D),
                                                shape: BoxShape.circle,
                                                border: Border.all(
                                                  color: Colors.white,
                                                  width: 2,
                                                ),
                                              ),
                                              child: const Icon(
                                                Icons.play_arrow, // İkon
                                                color: Colors.white,
                                                size: 30, // İkon boyutu
                                              ),
                                            ),
                                          ),
                                        ),
                                        20.horizontalSpace,
                                        Expanded(
                                          child: Column(
                                            crossAxisAlignment:
                                                CrossAxisAlignment.start,
                                            children: [
                                              Text(
                                                data.results[index].title,
                                                style: context
                                                    .textTheme.headlineSmall!
                                                    .copyWith(
                                                  fontFamily: FontFamily
                                                      .JosefinSans.value,
                                                  fontWeight: fWeightBold,
                                                  color:
                                                      const Color(0xff133B56),
                                                ),
                                              ),
                                              10.verticalSpace,
                                              Text(
                                                data.results[index].description,
                                                style: context
                                                    .textTheme.bodyLarge!
                                                    .copyWith(
                                                  fontFamily: FontFamily
                                                      .JosefinSans.value,
                                                  fontWeight: fWeightNormal,
                                                  color:
                                                      const Color(0xff133B56),
                                                ),
                                                maxLines: 2,
                                                overflow: TextOverflow.ellipsis,
                                              ),
                                            ],
                                          ),
                                        ),
                                        16.horizontalSpace,
                                      ],
                                    ),
                                  ),
                                )
                              : const Center(
                                  child: CircularProgressIndicator(
                                    color: Colors.white,
                                  ),
                                );
                        },
                      ),
                    ),
                  );
                },
                error: (error, stackTrace) {
                  return Center(
                    child: Text(
                      'Xəta',
                      style: context.textTheme.headlineMedium!.copyWith(
                        color: const Color(0xff133B56),
                      ),
                    ),
                  );
                },
                loading: () {
                  return const Center(
                    child: CircularProgressIndicator(
                      color: Colors.white,
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

error:

```
flutter: "PodGetXVideoController" not found. You need to call "Get.put(PodGetXVideoController())" or "Get.lazyPut(()=>PodGetXVideoController())"
flutter: #0      GetInstance.find (package:get/get_instance/src/get_instance.dart:306)
flutter: #1      Inst.find (package:get/get_instance/src/extension_instance.dart:69)
flutter: #2      _MobileOverlay.build (package:last_pod_player/src/widgets/core/overlays/mobile_overlay.dart:14)
flutter: #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:5557)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #6      StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #8      Element.updateChildren (package:flutter/src/widgets/framework.dart:3976)
flutter: #9      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6929)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #14     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #16     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
flutter: #19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
flutter: #21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905)
flutter: #22     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136)
flutter: #23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443)
flutter: #24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392)
flutter: #25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313)
flutter: #26     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171)
flutter: #27     _invoke (dart:ui/hooks.dart:312)
flutter: #28     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
flutter: #29     _drawFrame (dart:ui/hooks.dart:283)
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

**Comment by leonardmatasel** [comment]
You could give [omni_video_player](https://pub.dev/packages/omni_video_player) a try — supports YouTube, Vimeo, and more

**Comment by xurc** [comment]
Here is the fix: https://github.com/newtaDev/pod_player/issues/168#issuecomment-2118775815

There's a fix for this issue. I made it for the original repository, but the author disappeared. Could @ayahsujana please include this fix?
